package com.nevertiree.business.dao;

import com.nevertiree.domain.Book;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface BookMapper {

    // 自建代码 开始

    // TODO: 2017/1/1 MyBatis如何返回List<Book> ？？？ 
    
    // 根据书名查询书籍信息 返回List<Book> 
//    @Select({
//            "select * from book where name = #{topN,jdbcType=CHAR} order by vote desc;"
//    })
//    @ResultMap("com.nevertiree.business.dao.BookMapper.BookList")
    List<Book> queryBookByName(String name);
    
    // 根据阅读人数查询书籍 返回List<Book> 
//    @Select({
//            "select * from book order by vote desc limit 0,#{topN,jdbcType=INTEGER};"
//    })
//    @ResultMap("com.nevertiree.business.dao.BookMapper.Book")
    List<Book> queryBookByVoteDesc(int topN);
    
//    // 根据书籍评分人数查询书籍 返回List<Book>
//    @Select({
//            "select * from book order by score desc limit 0,#{topN,jdbcType=INTEGER};"
//    })
//    @ResultMap("com.nevertiree.business.dao.BookMapper.Book")
    List<Book> queryBookByScoreDesc(int topN);

    // 自建代码 终止
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @Delete({
        "delete from book",
        "where isbn = #{isbn,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @Insert({
        "insert into book (isbn, name, ",
        "vote, score, rank5, ",
        "rank4, rank3, rank2, ",
        "rank1)",
        "values (#{isbn,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{vote,jdbcType=INTEGER}, #{score,jdbcType=DOUBLE}, #{rank5,jdbcType=DOUBLE}, ",
        "#{rank4,jdbcType=DOUBLE}, #{rank3,jdbcType=DOUBLE}, #{rank2,jdbcType=DOUBLE}, ",
        "#{rank1,jdbcType=DOUBLE})"
    })
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    // 根据ISBN书号查询书籍信息
    @Select({
        "select",
        "isbn, name, vote, score, rank5, rank4, rank3, rank2, rank1",
        "from book",
        "where isbn = #{isbn,jdbcType=CHAR}"
    })
    @ResultMap("com.nevertiree.business.dao.BookMapper.BaseResultMap")
    Book selectByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @Update({
        "update book",
        "set name = #{name,jdbcType=VARCHAR},",
          "vote = #{vote,jdbcType=INTEGER},",
          "score = #{score,jdbcType=DOUBLE},",
          "rank5 = #{rank5,jdbcType=DOUBLE},",
          "rank4 = #{rank4,jdbcType=DOUBLE},",
          "rank3 = #{rank3,jdbcType=DOUBLE},",
          "rank2 = #{rank2,jdbcType=DOUBLE},",
          "rank1 = #{rank1,jdbcType=DOUBLE}",
        "where isbn = #{isbn,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Book record);
}