use MAJOR;
create table MAJOR_TOTAL
(
	MAJOR_CODE int NOT NULL PRIMARY KEY,
	MAJOR_NAME VARCHAR(30) NOT NULL,
	MAJOR_TYPE VARCHAR(30) NOT NULL,
	MAJOR_LEVEL VARCHAR(10) NOT NULL,
	BK_NUM int NOT NULL,
	ZK_NUM int NOT NULL
)
;